"""
client_example.py - Example Python client for Kokoro-82M WebSocket Streaming TTS API
Demonstrates:
  1. Connecting to the bidirectional WebSocket endpoint (ws://localhost:8001/ws/tts).
  2. Simulating real-time token-by-token LLM output streaming.
  3. Receiving raw 16-bit PCM audio chunks continuously as they are synthesized.
  4. Playing audio live through speakers with zero latency jitter and/or saving to WAV.
"""

import sys

# Ensure UTF-8 output encoding across Windows/Linux terminals
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

import time
import json
import asyncio
import argparse
import numpy as np
import soundfile as sf

# Optional live speaker playback support
try:
    import sounddevice as sd
    PLAYBACK_AVAILABLE = True
except ImportError:
    PLAYBACK_AVAILABLE = False


# Sample conversational text for streaming demonstration
DEFAULT_STREAM_TEXT = (
    "Hello there! This is a live demonstration of streaming text to speech. "
    "As tokens are generated by your language model, they are immediately streamed over WebSockets, "
    "chunked on natural boundaries, and synthesized into fluid, twenty-four kilohertz audio. "
    "Notice how quickly speech playback begins, keeping response latency astonishingly low!"
)


async def run_streaming_client(
    server_url: str = "ws://localhost:8001/ws/tts",
    voice: str = "af_heart",
    speed: float = 1.0,
    text: str = DEFAULT_STREAM_TEXT,
    token_delay: float = 0.04,  # ~40ms delay per token to simulate realistic LLM streaming
    play_audio: bool = True,
    output_wav: str = "streamed_output.wav"
):
    """
    Connect to Kokoro WebSocket TTS API, stream text tokens, and handle streamed audio chunks.
    """
    try:
        import websockets
    except ImportError:
        print("❌ Error: 'websockets' package is required. Install with: pip install websockets")
        return

    # Build WebSocket URL with query parameters
    query_params = f"?voice={voice}&speed={speed}&format=pcm"
    full_url = f"{server_url}{query_params}"

    print("\n" + "=" * 70)
    print("🎙️ Kokoro-82M Streaming TTS Python Client")
    print(f"   Connecting to: {full_url}")
    print(f"   Voice: {voice} | Speed: {speed}x | LLM Token Delay: {token_delay*1000:.0f}ms")
    print("=" * 70 + "\n")

    audio_chunks = []
    sample_rate = 24000
    first_audio_time = None
    stream_start_time = None

    # Audio playback queue for live speaker output
    playback_queue = asyncio.Queue()

    async def audio_playback_task():
        """Consumes raw PCM audio chunks and plays them through the speaker."""
        while True:
            chunk = await playback_queue.get()
            if chunk is None:
                playback_queue.task_done()
                break
            if play_audio and PLAYBACK_AVAILABLE:
                # Convert 16-bit PCM bytes back to float32 for sounddevice playback
                int16_data = np.frombuffer(chunk, dtype=np.int16)
                float32_data = int16_data.astype(np.float32) / 32768.0
                # Play chunk synchronously on audio thread
                await asyncio.to_thread(sd.play, float32_data, sample_rate)
                await asyncio.to_thread(sd.wait)
            playback_queue.task_done()

    playback_worker = asyncio.create_task(audio_playback_task())

    async with websockets.connect(full_url) as ws:
        # 1. Receive handshake message
        handshake_raw = await ws.recv()
        handshake = json.loads(handshake_raw)
        sample_rate = handshake.get("sample_rate", 24000)
        print(f"✅ [Handshake] Connected! Server Device: {handshake.get('device', 'unknown').upper()} | Sample Rate: {sample_rate}Hz\n")

        # 2. Coroutine to receive audio chunks & metadata from server
        async def receive_audio_stream():
            nonlocal first_audio_time
            chunks_received = 0
            while True:
                try:
                    message = await ws.recv()
                    if isinstance(message, bytes):
                        # Binary raw 16-bit PCM chunk received!
                        now = time.time()
                        if first_audio_time is None and stream_start_time is not None:
                            first_audio_time = now
                            ttfa_ms = (first_audio_time - stream_start_time) * 1000.0
                            print(f"\n🚀 [TTFA] Time To First Audio: {ttfa_ms:.1f}ms\n")

                        chunks_received += 1
                        int16_arr = np.frombuffer(message, dtype=np.int16)
                        audio_chunks.append(int16_arr)

                        # Queue for immediate playback
                        if play_audio and PLAYBACK_AVAILABLE:
                            await playback_queue.put(message)

                    elif isinstance(message, str):
                        # JSON control message
                        evt = json.loads(message)
                        evt_type = evt.get("type")
                        if evt_type == "chunk_start":
                            print(f"⚡ [Server] Synthesizing Chunk #{evt['chunk_id']}: \"{evt['text']}\"")
                        elif evt_type == "chunk_end":
                            print(f"   └─ Ready in {evt['latency_ms']}ms | Duration: {evt['duration_sec']}s | RTF: {evt['rtf']}x")
                        elif evt_type == "done":
                            print(f"\n🎉 [Complete] Total Chunks: {evt['total_chunks']} | Audio Duration: {evt['total_duration_sec']}s | Total Synth Time: {evt['total_synthesis_time_sec']}s | RTF: {evt['rtf']}x")
                            break
                        elif evt_type == "interrupted":
                            print("⏹️ [Server] Stream was interrupted.")
                            break
                        elif evt_type == "error":
                            print(f"❌ [Server Error]: {evt.get('error')}")
                            break
                except websockets.ConnectionClosed:
                    break

        # 3. Coroutine to stream LLM tokens to server
        async def send_text_tokens():
            nonlocal stream_start_time
            # Split text into token-like words
            words = text.split(" ")
            print(f"▶️ Streaming {len(words)} tokens to server...")
            stream_start_time = time.time()

            for i, word in enumerate(words):
                # Add trailing space except for last word
                token = word + (" " if i < len(words) - 1 else "")
                await ws.send(json.dumps({"type": "text", "text": token}))
                if token_delay > 0:
                    await asyncio.sleep(token_delay)

            # Signal that the LLM response stream has finished
            print("📤 Sending 'flush' signal to server...")
            await ws.send(json.dumps({"type": "flush"}))

        # Run sender and receiver concurrently
        receiver_task = asyncio.create_task(receive_audio_stream())
        sender_task = asyncio.create_task(send_text_tokens())

        await asyncio.gather(sender_task, receiver_task)

        # Signal audio playback worker to finish
        await playback_queue.put(None)
        await playback_worker

    # 4. Save aggregated audio to WAV file
    if output_wav and audio_chunks:
        full_int16 = np.concatenate(audio_chunks)
        full_float32 = full_int16.astype(np.float32) / 32768.0
        sf.write(output_wav, full_float32, sample_rate)
        total_duration = len(full_float32) / sample_rate
        print(f"\n💾 Saved full audio ({total_duration:.2f}s) to: {output_wav}")


def main():
    parser = argparse.ArgumentParser(
        description="Kokoro-82M WebSocket Streaming TTS Client",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    parser.add_argument("--url", type=str, default="ws://localhost:8001/ws/tts", help="WebSocket server URL")
    parser.add_argument("--voice", "-v", type=str, default="af_heart", help="Voice ID or blend")
    parser.add_argument("--speed", "-s", type=float, default=1.0, help="Speech playback speed")
    parser.add_argument("--text", "-t", type=str, default=DEFAULT_STREAM_TEXT, help="Text to stream and synthesize")
    parser.add_argument("--token-delay", type=float, default=0.04, help="Simulated LLM token delay in seconds")
    parser.add_argument("--no-play", action="store_true", help="Disable real-time speaker audio playback")
    parser.add_argument("--output", "-o", type=str, default="streamed_output.wav", help="Path to save output WAV file")

    args = parser.parse_args()

    asyncio.run(
        run_streaming_client(
            server_url=args.url,
            voice=args.voice,
            speed=args.speed,
            text=args.text,
            token_delay=args.token_delay,
            play_audio=not args.no_play,
            output_wav=args.output
        )
    )


if __name__ == "__main__":
    main()
